name: build_release

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore Source/Source.sln
    - name: Build
      run: dotnet build Source/Source.sln --no-restore --configuration Release
    - name: Share artifact
      uses: actions/upload-artifact@v6.0.0
      with:
        retention-days: 1
        compression-level: 9
        path: ./Assemblies/ProjectRimFactory.dll
