name: .NET

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore Source/Source.sln
    - name: Build
      run: dotnet build Source/Source.sln --no-restore
    - uses: actions/upload-artifact@v2
      with:
        name: ProjectRimFactory.dll
        path: Assemblies/ProjectRimFactory.dll
